import numpy as np
a=np.array(["fawad","li","bilal"])
print(a)
print(a.dtype)
a=np.array([1,2,3],dtype='bool')
print(a.dtype)
b=a.astype(float)
print(b)
e=b.view()
e[2]=4
print(e)
print(b)
f=np.array([1,2,2,3])
print(f)
print(f.ndim)
s=f.reshape(2,2)
print(s.ndim)
# a=np.array(["bilal","ali","saad","fawad"])
# print(a)
# print(a.dtype)
# b=np.array(["1","2","3","4"])
# print(b.dtype)
# c=np.array([1,2,3,4],dtype='S')
# print(c.dtype)
# f=np.array([3.9,0,0.3,0.4],dtype='f')
# print(f)
# print(f.dtype)
# d=f.astype(bool)
# print(d)
# e=f.view()
# print(e)
# e[0]=34
# print(e)
# f=np.array([[2,3],[3,5],[4,5]])
# print(f.shape)
# g=np.array([1,2,3,4,5,6,7,8],)
# q=g.reshape(2,2,2)
# w=q.reshape(-1)
# print(g)
# print(q)
# print(w)
# print(g.shape)
# print(g.ndim)
# print(q.shape)
# print(q.ndim)
# print(np.array([range(99)]))

